adminUsername=''
adminPass=''
username='anesu+contractor11@velocityinc.tech'
contrPass='mavaraEwhite22_'
signuplink='https://alpha.jobbliss.com/signup'
signinlink='https://alpha.jobbliss.com/signin'
dashboardlink='https://alpha.jobbliss.com/dashboard'
firstName='Patrick'
LastName='Pakati'
forgotPwd='https://alpha.jobbliss.com/forgot-password'
contractorEmail='anesu+contractor@velocityinc.tech'
groupsLink='https://alpha.jobbliss.com/groups'
dbview = 'https://alpha.jobbliss.com/company_database/'

emailContent = 'emailContent.txt'
automationCSVResults='AutomationQA_Summary.csv'
groupName='Adekunle'

USERNAME = 'anesuchiodza@yahoo.com'
PASSWORD = 'testCase123_'
SEARCH = '********'
emailContractor = 'anesu+contractor85@velocityinc.tech'
fnameContractor = 'Contractor'
lnameContractor = 'NumberEightyFive'