name: build

on: [push]
  #pull_request:
   # types: [closed]
    #branches: [master]

jobs:
  build:
    name: copy
    runs-on: self-hosted
    steps:
      - name: copy
        run: |
          cp -r /QA-Automation/qaCommandCenter/ /data/QA-Automation/
      - name: run-app
        run: |
          cd /data/QA-Automation/qaCommandCenter
          python -m flask run --host=0.0.0.0 --port=5000

