name: build

on: [push]
  #pull_request:
   # types: [closed]
    #branches: [master]

jobs:
  build:
    name: copy
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: copy
        run: |
          pwd
          sudo cp -r /home/ubuntu/actions-runner/points-africa/QA-Automation/QA-Automation /data
      - name: run-app
        run: |
          cd /data/QA-Automation/qaCommandCenter
          fuser -k 5000/tcp
          python3 -m flask initdb
          python3 -m flask run --host=0.0.0.0 --port=5000 &

